import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import PageTransitionOverlays from "../components/PageTransition";
import { TransitionProvider } from "../components/TransitionProvider";
import Footer from "../components/Footer";

const montrealBook = localFont({
  src: "../public/fonts/PPNeueMontreal-Book.woff2",
  variable: "--font-montreal-book",
  display: "swap",
  weight: "400",
  style: "normal",
});

const montrealRegular = localFont({
  src: "../public/fonts/PPNeueMontreal-Regular.woff2",
  variable: "--font-montreal-regular",
  display: "swap",
  weight: "400",
  style: "normal",
});

const montrealMedium = localFont({
  src: "../public/fonts/PPNeueMontreal-Medium.woff2",
  variable: "--font-montreal-medium",
  display: "swap",
  weight: "500",
  style: "normal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montrealBook.variable} ${montrealRegular.variable} ${montrealMedium.variable} antialiased`}
        suppressHydrationWarning
      >
        <TransitionProvider>
          <Navbar />
          <div className="scroll-container">{children}</div>
          <Footer />
          <PageTransitionOverlays />
        </TransitionProvider>
      </body>
    </html>
  );
}
